// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6NzGOCOKAr7W5LhxSigvkkSiFzUyfkTE',
    appId: '1:286135986090:web:551255f148c86b0c04edd3',
    messagingSenderId: '286135986090',
    projectId: 'authenticator-695f1',
    authDomain: 'authenticator-695f1.firebaseapp.com',
    storageBucket: 'authenticator-695f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAafnV4ic_Vom1K6asYFEj8OSkC_JGs9nQ',
    appId: '1:286135986090:android:01a6efedfba8015a04edd3',
    messagingSenderId: '286135986090',
    projectId: 'authenticator-695f1',
    storageBucket: 'authenticator-695f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqPoA8l1wOC0ZM3ibkDcwz7bve1cAYXCc',
    appId: '1:286135986090:ios:312d556d716fde5f04edd3',
    messagingSenderId: '286135986090',
    projectId: 'authenticator-695f1',
    storageBucket: 'authenticator-695f1.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqPoA8l1wOC0ZM3ibkDcwz7bve1cAYXCc',
    appId: '1:286135986090:ios:312d556d716fde5f04edd3',
    messagingSenderId: '286135986090',
    projectId: 'authenticator-695f1',
    storageBucket: 'authenticator-695f1.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6NzGOCOKAr7W5LhxSigvkkSiFzUyfkTE',
    appId: '1:286135986090:web:522b877864d5ef0504edd3',
    messagingSenderId: '286135986090',
    projectId: 'authenticator-695f1',
    authDomain: 'authenticator-695f1.firebaseapp.com',
    storageBucket: 'authenticator-695f1.appspot.com',
  );
}
